### ISSUE TITLE
Issue de mejora

### ISSUE THREAD

**Issue by diego200092** [degoxec98/Trivia#4]
Me gustaria ver la cantidad de preguntas en la que he fallado y ver la nota final. 
![image](https://user-images.githubusercontent.com/113485447/190832369-7854cdf6-ac5c-4264-9d72-23917004f411.png)

**Comment by degoxec98** [comment]
Hola @diego200092,

Muchas gracias por tu sugerencia, el issue ya se está haciendo seguimiento en el siguiente issue #1 

Saludos
